import type { Question } from './types'

export const questions: Question[] = [
  {
    id: 'q-tell-me',
    text: 'Tell us about yourself.',
    departments: ['shared'],
    stages: ['screening', 'speed', 'oral'],
    competencies: ['selfKnowledge', 'motivation'],
    tip: '60–90 seconds. Present → relevant past → why fire → why you are ready. No life story novel.',
    sampleOutline:
      'Who you are now → 2–3 formative experiences → skills that transfer → why you are sitting here today.',
  },
  {
    id: 'q-why-ff',
    text: 'Why do you want to be a firefighter?',
    departments: ['shared'],
    stages: ['screening', 'speed', 'oral', 'leadership', 'chiefs'],
    competencies: ['motivation'],
    tip: 'Service + teamwork + craft. Avoid “adrenaline” and movie-fire romance. Tie to EMS-heavy reality.',
  },
  {
    id: 'q-why-efr',
    text: 'Why Eastside Fire & Rescue?',
    departments: ['efr'],
    stages: ['oral', 'leadership'],
    competencies: ['motivation', 'deptKnowledge'],
    tip: 'Partner model, multi-community service, values (URDS), WUI/tech/MIH — specific, not generic Eastside.',
  },
  {
    id: 'q-why-bfd',
    text: 'Why Bellingham Fire Department?',
    departments: ['bfd'],
    stages: ['speed', 'oral', 'chiefs'],
    competencies: ['motivation', 'deptKnowledge'],
    tip: 'Helping People Every Day in your words + EMS culture + neighborhoods + waterfront/county readiness.',
  },
  {
    id: 'q-helping-people',
    text: 'What does “Helping People Every Day” mean to you?',
    departments: ['bfd'],
    stages: ['speed', 'oral', 'chiefs'],
    competencies: ['motivation', 'customerService', 'deptKnowledge'],
    tip: 'Make it concrete: medical calls, dignity, follow-through, crew support — not a slogan.',
  },
  {
    id: 'q-strength',
    text: 'What is your greatest strength, and how would it show up on a crew?',
    departments: ['shared'],
    stages: ['screening', 'speed', 'oral'],
    competencies: ['selfKnowledge', 'teamwork'],
    tip: 'One strength + one short proof + how it helps the team tomorrow.',
  },
  {
    id: 'q-weakness',
    text: 'What is a weakness you are working on?',
    departments: ['shared'],
    stages: ['oral', 'leadership', 'chiefs'],
    competencies: ['selfKnowledge', 'failure'],
    tip: 'Real, not fake-humble. Show ownership and a concrete improvement habit.',
  },
  {
    id: 'q-conflict',
    text: 'Tell us about a time you had a conflict with a coworker or teammate.',
    departments: ['shared'],
    stages: ['oral', 'leadership'],
    competencies: ['conflict', 'teamwork'],
    tip: 'STAR. Stay respectful. Show listening, direct communication, and repaired working relationship.',
  },
  {
    id: 'q-integrity',
    text: 'Describe a time your integrity was tested.',
    departments: ['shared'],
    stages: ['oral', 'leadership', 'chiefs'],
    competencies: ['integrity'],
    tip: 'Unobserved honesty matters. Result should protect trust, even if costly.',
  },
  {
    id: 'q-mistake',
    text: 'Tell us about a mistake you made and what you learned.',
    departments: ['shared'],
    stages: ['oral', 'leadership', 'chiefs'],
    competencies: ['failure', 'integrity'],
    tip: 'Own it fully. Learning must transfer to firehouse/EMT academy life.',
  },
  {
    id: 'q-stress',
    text: 'Describe a time you performed under stress or time pressure.',
    departments: ['shared'],
    stages: ['oral', 'speed'],
    competencies: ['stress', 'selfKnowledge'],
    tip: 'Show composure process: prioritize, communicate, execute, debrief.',
  },
  {
    id: 'q-customer',
    text: 'Tell us about a time you provided excellent customer service or compassion.',
    departments: ['shared'],
    stages: ['oral', 'speed'],
    competencies: ['customerService', 'diversity'],
    tip: 'Dignity of the person > task completion. Matches BFD mission and EF&R Respect.',
  },
  {
    id: 'q-diversity',
    text: 'How do you work with people different from you?',
    departments: ['shared'],
    stages: ['oral', 'chiefs'],
    competencies: ['diversity', 'teamwork'],
    tip: 'Specific example. Curiosity, respect, and better team outcomes.',
  },
  {
    id: 'q-team',
    text: 'Give an example of being a good teammate when it was hard.',
    departments: ['shared'],
    stages: ['screening', 'speed', 'oral'],
    competencies: ['teamwork'],
    tip: 'Firehouses live together — show reliability, humility, and shared standards.',
  },
  {
    id: 'q-prep',
    text: 'What have you done to prepare?',
    departments: ['shared'],
    stages: ['screening', 'speed', 'oral'],
    competencies: ['motivation', 'selfKnowledge'],
    tip: 'Inventory: fitness, ride-alongs/research, certifications, volunteering, studying EF&R specifically.',
    sampleOutline:
      'Physical training → certifications/education → agency research (values, partner model) → life experience that proves service.',
  },
  {
    id: 'q-efr-traits',
    text: 'What traits do you bring?',
    departments: ['efr'],
    stages: ['screening'],
    competencies: ['selfKnowledge', 'teamwork', 'fit'],
    tip: 'Pick 2–3 traits tied to URDS (Unity, Respect, Determination, Safety). One sentence each + one quick proof — not a laundry list.',
    sampleOutline:
      'Trait → how it shows on a crew tomorrow → tie to an EF&R value or look-for.',
  },
  {
    id: 'q-station-life',
    text: 'What do you understand about living and working in a firehouse?',
    departments: ['shared'],
    stages: ['oral', 'leadership', 'chiefs'],
    competencies: ['fit', 'teamwork'],
    tip: 'Shared space, chores, sleep interruption, mutual respect, training culture.',
  },
  {
    id: 'q-ems-reality',
    text: 'Most calls are medical. How do you feel about that?',
    departments: ['shared'],
    stages: ['oral', 'speed', 'chiefs'],
    competencies: ['motivation', 'customerService'],
    tip: 'Enthusiasm for people-care. Especially critical for Bellingham (~85% EMS).',
  },
  {
    id: 'q-values-efr',
    text: 'Which EF&R value do you connect with most, and why?',
    departments: ['efr'],
    stages: ['oral', 'leadership'],
    competencies: ['deptKnowledge', 'selfKnowledge'],
    tip: 'Pick one value, prove it with a story, bridge to crew life.',
  },
  {
    id: 'q-scenario-unsafe',
    text: 'A senior firefighter tells you to do something you believe is unsafe. What do you do?',
    departments: ['shared'],
    stages: ['oral', 'leadership', 'chiefs'],
    competencies: ['scenario', 'integrity', 'leadership'],
    tip: 'Safety → clarify → speak up respectfully → chain of command → never freelances recklessly.',
  },
  {
    id: 'q-scenario-theft',
    text: 'You see a coworker take something from a patient or the station. What do you do?',
    departments: ['shared'],
    stages: ['oral', 'leadership', 'chiefs'],
    competencies: ['scenario', 'integrity'],
    tip: 'Protect the public and the badge. Report through proper channels; do not cover it up.',
  },
  {
    id: 'q-scenario-impaired',
    text: 'You suspect a crew member is impaired coming on shift. What do you do?',
    departments: ['shared'],
    stages: ['oral', 'leadership', 'chiefs'],
    competencies: ['scenario', 'integrity'],
    tip: 'Public safety first. Notify officer/chain of command immediately. Do not ignore.',
  },
  {
    id: 'q-scenario-conflict-public',
    text: 'A patient or family member is hostile toward you. How do you handle it?',
    departments: ['shared'],
    stages: ['oral'],
    competencies: ['scenario', 'customerService', 'stress'],
    tip: 'Calm voice, space, safety, de-escalation, help still offered within policy.',
  },
  {
    id: 'q-failure-fit',
    text: 'Why should we hire you over other candidates?',
    departments: ['shared'],
    stages: ['oral', 'leadership', 'chiefs'],
    competencies: ['motivation', 'fit'],
    tip: 'Humble confidence. Specific traits + proof + department fit — not arrogance.',
  },
  {
    id: 'q-questions-for-us',
    text: 'Do you have any questions for us?',
    departments: ['shared'],
    stages: ['oral', 'leadership', 'chiefs'],
    competencies: ['motivation', 'deptKnowledge'],
    tip: 'Ask about recruit expectations, training culture, or what great probationary firefighters do — not pay/benefits first.',
  },
  {
    id: 'q-long-term',
    text: 'Where do you see yourself in five years?',
    departments: ['shared'],
    stages: ['leadership', 'chiefs'],
    competencies: ['fit', 'motivation'],
    tip: 'Competent firefighter first. Growth without sounding like you are skipping apprenticeship.',
  },
  {
    id: 'q-diversity-bfd',
    text: 'How would you contribute to an inclusive crew and community?',
    departments: ['bfd'],
    stages: ['oral', 'chiefs'],
    competencies: ['diversity', 'teamwork'],
    tip: 'Align to BFD core values: heard/seen, communication, grace while learning.',
  },
  {
    id: 'q-mih',
    text: 'EF&R invests in community and integrated health beyond the emergency. Why does that matter?',
    departments: ['efr'],
    stages: ['oral', 'leadership'],
    competencies: ['deptKnowledge', 'customerService'],
    tip: 'Shows research. Connect compassion + prevention/follow-up to mission.',
  },
]

