import type { StarStory } from './types'

/** Fill these with your real stories. Spoken versions should be ~60–90 seconds aloud. */
export const stories: StarStory[] = [
  {
    id: 'story-teamwork',
    title: 'Hard teamwork when it counted',
    competencies: ['teamwork'],
    efrValues: ['Unity', 'Determination'],
    bfdLookFors: ['Teamwork and Cooperation', 'Results'],
    situation: '[REPLACE] Set the scene — team, stakes, constraint.',
    task: '[REPLACE] What were you responsible for?',
    action: '[REPLACE] What did YOU specifically do? Use “I” verbs.',
    result: '[REPLACE] Measurable or clear outcome for the team/customer.',
    lesson: 'On a fire crew I will put the team mission ahead of ego and communicate early.',
    spokenVersion:
      '[REPLACE] Write the version you will actually say out loud. Practice until it is natural, not memorized-robot.',
    placeholder: true,
  },
  {
    id: 'story-conflict',
    title: 'Conflict handled with respect',
    competencies: ['conflict', 'teamwork'],
    efrValues: ['Respect', 'Unity'],
    bfdLookFors: ['Teamwork and Cooperation', 'Communication'],
    situation: '[REPLACE]',
    task: '[REPLACE]',
    action: '[REPLACE]',
    result: '[REPLACE]',
    lesson: 'I address issues directly and respectfully so the working relationship gets stronger.',
    spokenVersion: '[REPLACE]',
    placeholder: true,
  },
  {
    id: 'story-integrity',
    title: 'Integrity when no one was watching',
    competencies: ['integrity'],
    efrValues: ['Safety', 'Determination'],
    bfdLookFors: ['Ethical accountability', 'Standards'],
    situation: '[REPLACE]',
    task: '[REPLACE]',
    action: '[REPLACE]',
    result: '[REPLACE]',
    lesson: 'Trust is the job. I will protect it even when it costs me convenience.',
    spokenVersion: '[REPLACE]',
    placeholder: true,
  },
  {
    id: 'story-customer',
    title: 'Compassion / customer care',
    competencies: ['customerService', 'diversity'],
    efrValues: ['Respect'],
    bfdLookFors: ['Desire to Serve', 'Diversity'],
    situation: '[REPLACE]',
    task: '[REPLACE]',
    action: '[REPLACE]',
    result: '[REPLACE]',
    lesson: 'Helping people means dignity and follow-through, not just completing a task.',
    spokenVersion: '[REPLACE]',
    placeholder: true,
  },
  {
    id: 'story-stress',
    title: 'Composure under pressure',
    competencies: ['stress'],
    efrValues: ['Determination', 'Safety'],
    bfdLookFors: ['Standards', 'Results'],
    situation: '[REPLACE]',
    task: '[REPLACE]',
    action: '[REPLACE]',
    result: '[REPLACE]',
    lesson: 'I slow my thinking, prioritize, communicate, and finish the critical work.',
    spokenVersion: '[REPLACE]',
    placeholder: true,
  },
  {
    id: 'story-failure',
    title: 'Mistake owned and fixed',
    competencies: ['failure', 'integrity'],
    efrValues: ['Determination', 'Respect'],
    bfdLookFors: ['Grace while learning', 'Results'],
    situation: '[REPLACE]',
    task: '[REPLACE]',
    action: '[REPLACE]',
    result: '[REPLACE]',
    lesson: 'I own mistakes fast, repair the impact, and change the habit.',
    spokenVersion: '[REPLACE]',
    placeholder: true,
  },
  {
    id: 'story-diversity',
    title: 'Working across difference',
    competencies: ['diversity', 'teamwork'],
    efrValues: ['Unity', 'Respect'],
    bfdLookFors: ['Diversity', 'Cultural understanding'],
    situation: '[REPLACE]',
    task: '[REPLACE]',
    action: '[REPLACE]',
    result: '[REPLACE]',
    lesson: 'I listen first and adapt so every person gets solid service and every teammate is heard.',
    spokenVersion: '[REPLACE]',
    placeholder: true,
  },
  {
    id: 'story-grit',
    title: 'Physical or academic grit',
    competencies: ['motivation', 'selfKnowledge'],
    efrValues: ['Determination'],
    bfdLookFors: ['Standards', 'Results'],
    situation: '[REPLACE]',
    task: '[REPLACE]',
    action: '[REPLACE]',
    result: '[REPLACE]',
    lesson: 'I build capacity with consistent training and honest self-assessment.',
    spokenVersion: '[REPLACE]',
    placeholder: true,
  },
  {
    id: 'story-leadership',
    title: 'Informal leadership / initiative',
    competencies: ['leadership', 'teamwork'],
    efrValues: ['Unity', 'Determination'],
    bfdLookFors: ['Results', 'Be a resource'],
    situation: '[REPLACE]',
    task: '[REPLACE]',
    action: '[REPLACE]',
    result: '[REPLACE]',
    lesson: 'I lead from my seat — initiative without undermining the officer.',
    spokenVersion: '[REPLACE]',
    placeholder: true,
  },
  {
    id: 'bio-tell-me',
    title: 'Tell me about yourself (bio)',
    competencies: ['selfKnowledge', 'motivation'],
    efrValues: ['Determination'],
    bfdLookFors: ['Desire to Serve'],
    situation: 'N/A — this is your bio, not a STAR story.',
    task: 'Deliver a clear 60–90s introduction.',
    action: '[REPLACE] Who you are, relevant background, why fire, why now.',
    result: 'Panel understands your path and readiness.',
    lesson: 'Clarity beats autobiography.',
    spokenVersion:
      '[REPLACE] Write your spoken bio here. Keep it tight. End on why you are ready for THIS department.',
    placeholder: true,
  },
]

export const competencyLabels: Record<string, string> = {
  motivation: 'Motivation',
  selfKnowledge: 'Self-knowledge',
  teamwork: 'Teamwork',
  integrity: 'Integrity',
  conflict: 'Conflict',
  stress: 'Stress / composure',
  customerService: 'Customer service',
  diversity: 'Diversity & inclusion',
  leadership: 'Leadership',
  failure: 'Failure / learning',
  deptKnowledge: 'Department knowledge',
  scenario: 'Scenario judgment',
  fit: 'Fit / station life',
}
